

export const LOGIN_USER_REQUEST = 'LOGIN_USER_REQUEST';
export const LOGIN_USER_FAILURE = 'LOGIN_USER_FAILURE';
export const LOGIN_USER_SUCCESS = 'LOGIN_USER_SUCCESS';
export const LOGOUT_USER = 'LOGOUT_USER';
export const FETCH_PROTECTED_DATA_REQUEST = 'FETCH_PROTECTED_DATA_REQUEST';
export const RECEIVE_PROTECTED_DATA = 'RECEIVE_PROTECTED_DATA';

//export const INITIAL_SIZING = 'INITIAL_SIZING';
//export const WINDOW_RESIZED = 'WINDOW_RESIZED';

export const SELECT_TRANSPORTATION = 'SELECT_TRANSPORTATION';
export const UPDATE_TRANSPORTATION_CATALOG_FILTER = 'UPDATE_TRANSPORTATION_CATALOG_FILTER';

export const TRANSPORTATION_CATALOG_REQUEST = 'TRANSPORTATION_CATALOG_REQUEST';
export const TRANSPORTATION_CATALOG_FAILURE = 'TRANSPORTATION_CATALOG_FAILURE';
export const TRANSPORTATION_CATALOG_SUCCESS = 'TRANSPORTATION_CATALOG_SUCCESS';


export const HUBS_CATALOG_REQUEST = 'HUBS_CATALOG_REQUEST';
export const HUBS_CATALOG_SUCCESS = 'HUBS_CATALOG_SUCCESS';
export const HUBS_CATALOG_FAILURE = 'HUBS_CATALOG_FAILURE';
export const UPDATE_HUBS_CATALOG = 'UPDATE_HUBS_CATALOG';
